Repository boostcampwm-2024/web11-road_to_friendly, pull requests merged in 2024-11, with the labels that each got.

#37 frontend 프로젝트 생성(Vite+TypeScript)
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: 개발환경 설정, FE

#39 feat: 🎸 eslint + prettier 설정 추가, 폴더구조 설정
  frontend/.prettierignore
  frontend/.prettierrc
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/tsconfig.app.json
  frontend/tsconfig.node.json
Labels: 개발환경 설정, FE

#40 feat: 🎸 emotion, zustand, react router dom 환경설정
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: 개발환경 설정, FE

#43 랜딩 페이지 UI 구현
  frontend/src/App.tsx
  frontend/src/assets/landing-clap.png
  frontend/src/components/common/Header.tsx
  frontend/src/components/common/index.ts
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/LandingPage.tsx
  frontend/src/styles/GlobalStyle.tsx
  frontend/src/styles/Variables.ts
Labels: 방 개설 및 참여, FE

#42 Toast 메시지 컴포넌트 구현
  frontend/src/assets/icons/check.svg
  frontend/src/assets/icons/close.svg
  frontend/src/assets/icons/warn.svg
  frontend/src/components/common/Toast.tsx
  frontend/src/components/common/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useTimeout.ts
Labels: 방 개설 및 참여, FE

#46 버튼 hover 시 애니메이션 추가, 공유 버튼 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/check.svg
  frontend/src/assets/icons/close.svg
  frontend/src/assets/icons/link.svg
  frontend/src/assets/icons/warn.svg
  frontend/src/components/ShareButton.tsx
  frontend/src/components/common/Toast.tsx
  frontend/src/components/index.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/styles/animation.ts
  frontend/src/styles/index.ts
  frontend/src/vite-env.d.ts
  frontend/vite.config.ts
Labels: 방 개설 및 참여, FE

#50 로딩 스피너 및 페이지 구현
  frontend/src/components/RoomCreateButton.tsx
  frontend/src/components/common/LoadingSpinner.tsx
  frontend/src/components/common/LoadingSpinnerWave.tsx
  frontend/src/components/common/Toast.tsx
  frontend/src/components/common/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useIndex.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/room/room.tsx
  frontend/src/styles/animation.ts
  frontend/src/styles/index.ts
  frontend/src/utils/index.ts
  frontend/src/utils/parseNumberAndUnit.ts
Labels: 방 개설 및 참여, FE

#51 flex wrapper 재사용 스타일 추가, 질문을 표시할 QuestionView 구현, Header 컴포넌트에 paddingY prop 추가
  frontend/src/components/ParticipantListSidebar.tsx
  frontend/src/components/QuestionStartButton.tsx
  frontend/src/components/RoomCreateButton.tsx
  frontend/src/components/RoomNotFound.tsx
  frontend/src/components/ShareButton.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/room/hostView.tsx
  frontend/src/pages/room/questionsView.tsx
  frontend/src/pages/room/room.tsx
  frontend/src/stores/questions.ts
  frontend/src/styles/flex.ts
  frontend/src/styles/index.ts
  frontend/src/types/index.ts
  frontend/src/types/question.ts
Labels: 주제 답변 및 실시간 키워드 표시, FE

#55 방장이 '시작하기' 버튼 클릭 시 질문 리스트 표시 및 타이머 기능 구현, 절대경로 사용 설정, eslint import 순서 규칙 설정
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/icons/clock.svg
  frontend/src/components/ParticipantListSidebar.tsx
  frontend/src/components/QuestionStartButton.tsx
  frontend/src/components/RoomCreateButton.tsx
  frontend/src/components/RoomNotFound.tsx
  frontend/src/components/ShareButton.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/common/LoadingSpinner.tsx
  frontend/src/components/common/LoadingSpinnerWave.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/components/common/Toast.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/main.tsx
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/room/hostView.tsx
  frontend/src/pages/room/participantView.tsx
  frontend/src/pages/room/questionsView.tsx
  frontend/src/pages/room/room.tsx
  frontend/src/stores/index.ts
  frontend/src/stores/participants.ts
  frontend/src/stores/questions.ts
  frontend/src/stores/radius.ts
  frontend/src/stores/socket.ts
  frontend/src/styles/flex.ts
  frontend/src/utils/index.ts
  frontend/src/utils/time.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: 주제 답변 및 실시간 키워드 표시, 개발환경 설정, FE

#72 실시간 키워드 표시
  frontend/src/pages/room/KeywordsView.tsx
  frontend/src/pages/room/questionsView.tsx
  frontend/src/pages/room/room.tsx
  frontend/src/stores/keywords.ts
  frontend/src/types/index.ts
  frontend/src/types/keyword.tsx
  frontend/src/types/question.ts
Labels: 주제 답변 및 실시간 키워드 표시, FE

#76 결과 페이지(공통관심사 통계) 추가, room 컴포넌트 리팩토링
  frontend/src/components/ParticipantListSidebar.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/hooks/useParticipants.ts
  frontend/src/pages/room/KeywordsView.tsx
  frontend/src/pages/room/resultInstruction.tsx
  frontend/src/pages/room/resultView.tsx
  frontend/src/pages/room/room.tsx
  frontend/src/pages/room/roomIntroView.tsx
  frontend/src/stores/participants.ts
  frontend/src/stores/radius.ts
  frontend/src/types/ParticipantItem.ts
  frontend/src/types/index.ts
  frontend/src/types/keyword.ts
  frontend/src/types/participant.ts
  frontend/src/utils/index.ts
  frontend/src/utils/participantUtils.ts
Labels: 주제 답변 및 실시간 키워드 표시, FE

#81 키워드 송신, 수신기능 서버와 연결 및 store에 키워드 반영 로직 수정
  frontend/src/components/QuestionInput.tsx
  frontend/src/pages/room/KeywordsView.tsx
  frontend/src/pages/room/questionsView.tsx
  frontend/src/stores/keywords.ts
  frontend/src/types/index.ts
  frontend/src/types/keyword.ts
  frontend/src/types/question.ts
  frontend/src/types/response.ts
Labels: FE

#82 헤더에 프로필 버튼 추가 및 모달 컴포넌트 수정
  frontend/src/components/ParticipantListSidebar.tsx
  frontend/src/components/ProfileEditButton.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/constants.ts
  frontend/src/pages/room/resultView.tsx
  frontend/src/pages/room/room.tsx
Labels: FE

#85 키워드 그룹화, 그룹에 따른 스타일/ 애니메이션 임시 적용
  frontend/src/components/QuestionInput.tsx
  frontend/src/components/RoomCreateButton.tsx
  frontend/src/constants.ts
  frontend/src/pages/room/KeywordsView.tsx
  frontend/src/stores/keywords.ts
  frontend/src/styles/index.ts
  frontend/src/styles/keywordStyleMap.ts
  frontend/src/types/index.ts
  frontend/src/types/keyword.ts
Labels: FE

#102 FE gitAction 스크립트 작성
  .github/workflows/frontend-deploy.yml
Labels: 개발환경 설정, BE

#101 키워드 제출시 공감, 키워드 선택하여 공감/취소 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/QuestionInput.tsx
  frontend/src/components/QuestionStartButton.tsx
  frontend/src/pages/room/KeywordsView.tsx
  frontend/src/pages/room/questionsView.tsx
  frontend/src/services/apis.ts
  frontend/src/services/errorMessages.ts
  frontend/src/services/index.ts
  frontend/src/types/response.ts
Labels: 주제 답변 및 실시간 키워드 표시, FE

#117 컨텐츠 공유 모달 스켈레톤 코드 구현
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/image.svg
  frontend/src/assets/icons/leftArrow.svg
  frontend/src/assets/icons/youtube.svg
  frontend/src/components/common/ModalPortal.tsx
  frontend/src/components/common/ModalWithOverlay.tsx
  frontend/src/components/common/index.ts
  frontend/src/hooks/useModal.ts
  frontend/src/main.tsx
  frontend/src/pages/room/content-share/contentEnrollModal.tsx
  frontend/src/pages/room/content-share/contentShareView.tsx
  frontend/src/pages/room/content-share/enroll-modal-steps/chooseContentType.tsx
  frontend/src/pages/room/content-share/enroll-modal-steps/enrollImageContent.tsx
  frontend/src/pages/room/content-share/enroll-modal-steps/enrollYoutubeContent.tsx
  frontend/src/pages/room/content-share/enroll-modal-steps/index.ts
  frontend/src/pages/room/content-share/waitingListEmpty.tsx
  frontend/src/pages/room/content-share/waitingListInfo.tsx
Labels: 공통 관심사 확인 및 컨텐츠 공유, FE

#121 공유 알림, 공유 대기 알림 API 연결, 공유 컨텐츠 표시(이미지), 유튜브 컨텐츠 등록 기능 구현
  frontend/src/constants/youtube.ts
  frontend/src/main.tsx
  frontend/src/pages/room/content-share/contentEnrollModal.tsx
  frontend/src/pages/room/content-share/contentPresentSection.tsx
  frontend/src/pages/room/content-share/contentShareView.tsx
  frontend/src/pages/room/content-share/enroll-modal-steps/enrollYoutubeContent.tsx
  frontend/src/pages/room/content-share/enroll-modal-steps/index.ts
  frontend/src/pages/room/room.tsx
  frontend/src/services/apis.ts
  frontend/src/services/index.ts
  frontend/src/styles/Variables.ts
  frontend/src/tests/ContentShareView.test.tsx
  frontend/src/tests/setup.ts
  frontend/src/types/content.ts
  frontend/src/types/index.ts
  frontend/src/types/response.ts
  frontend/src/utils/index.ts
  frontend/src/utils/youtube.ts
  frontend/tsconfig.app.json
  frontend/vitest.config.ts
Labels: 공통 관심사 확인 및 컨텐츠 공유, FE

#126 BE github actions 적용
  .github/workflows/backend-deploy.yml
Labels: 개발환경 설정, BE

#125 권한제어를 위한 유튜브 플레이어 커스텀
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/arrow-left-s-line.svg
  frontend/src/assets/icons/arrow-right-s-line.svg
  frontend/src/assets/icons/check-line.svg
  frontend/src/assets/icons/closed-captioning-fill.svg
  frontend/src/assets/icons/equalizer-2-line.svg
  frontend/src/assets/icons/pause-line.svg
  frontend/src/assets/icons/play-fill.svg
  frontend/src/assets/icons/settings-4-fill.svg
  frontend/src/assets/icons/speed-fill.svg
  frontend/src/assets/icons/speed-mini-fill.svg
  frontend/src/assets/icons/triangle-fill.svg
  frontend/src/assets/icons/volume-down-fill.svg
  frontend/src/assets/icons/volume-mute-fill.svg
  frontend/src/components/Player/ControllBar.tsx
  frontend/src/components/Player/Player.tsx
  frontend/src/components/Player/SettingPanel.tsx
  frontend/src/components/Player/index.ts
  frontend/src/components/common/LoadingSpinner.tsx
  frontend/src/components/common/Slider.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/index.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/useFraction.ts
  frontend/src/pages/LoadingPage.tsx
  frontend/src/styles/Variables.ts
  frontend/src/utils/calculateUtils.ts
  frontend/src/utils/index.ts
  frontend/src/utils/parseNumberAndUnit.ts
Labels: FE

#127 이미지 전송 기능 구현
  frontend/src/assets/icons/deleteButton.svg
  frontend/src/pages/room/content-share/enroll-modal-steps/enrollImageContent.tsx
Labels: 공통 관심사 확인 및 컨텐츠 공유, FE

#133 유튜브 동기화 이벤트 구현
  backend/src/interests/definition/contentType.ts
  backend/src/interests/definition/interests.youtube.control.ts
  backend/src/interests/definition/time.unit.ts
  backend/src/interests/dto/interests.youtube.control.dto.ts
  backend/src/interests/dto/interests.youtube.control.response.dto.ts
  backend/src/interests/gateway/interests.gateway.ts
  backend/src/interests/service/interests.service.ts
Labels: 공통 관심사 확인 및 컨텐츠 공유, BE

#135 방 입장은 준비 상태에서만 가능하도록 수정, 불필요한 락과 비동기 제거, 닉네임 변경 버그 해결
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/clients/gateway/clients.gateway.ts
  backend/src/common/guard/participant.guard.ts
  backend/src/common/guard/phase.guard.ts
  backend/src/interests/gateway/interests.gateway.ts
  backend/src/interests/repository/interests.image.repository.ts
  backend/src/interests/repository/interests.in-memory.repository.ts
  backend/src/interests/repository/interests.repository.ts
  backend/src/interests/service/interests.service.ts
  backend/src/keywords/gateway/keywords.gateway.ts
  backend/src/keywords/repository/keywords.in-memory.repository.ts
  backend/src/keywords/service/keywords.service.ts
  backend/src/rooms/gateway/rooms.gateway.ts
  backend/src/rooms/repository/rooms.in-memory.repository.ts
  backend/src/rooms/service/rooms.service.ts
Labels: BE

#132 워드클라우드 UX 개선, 동일한 키워드를 재입력하여 공감 취소 처리 가능하도록 구현
  frontend/index.html
  frontend/src/components/QuestionInput.tsx
  frontend/src/pages/room/KeywordsView.tsx
  frontend/src/pages/room/content-share/contentShareView.tsx
  frontend/src/pages/room/questionsView.tsx
  frontend/src/stores/keywords.ts
Labels: enhancement, 주제 답변 및 실시간 키워드 표시, FE

#138 UI 버그 수정
  frontend/src/assets/icons/menu.svg
  frontend/src/components/ParticipantListSidebar.tsx
  frontend/src/components/ProfileEditButton.tsx
  frontend/src/components/QuestionInput.tsx
  frontend/src/components/QuestionStartButton.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/common/Modal.tsx
  frontend/src/pages/room/KeywordsView.tsx
  frontend/src/pages/room/questionsView.tsx
  frontend/src/pages/room/resultView.tsx
  frontend/src/pages/room/room.tsx
  frontend/src/stores/radius.ts
Labels: FE

#140 유튜브 동기화 구현, 서버와 연결, 플레이어 버그 픽스
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Player/ControllBar.tsx
  frontend/src/components/Player/ControllerSection.tsx
  frontend/src/components/Player/Player.tsx
  frontend/src/components/Player/SettingPanel.tsx
  frontend/src/components/Player/SharerDraggingIndicator.tsx
  frontend/src/components/Player/StateChangeIndicator.tsx
  frontend/src/components/Player/VideoOverlayToggle.tsx
  frontend/src/components/common/Slider.tsx
  frontend/src/components/common/Tooltip.tsx
  frontend/src/constants.ts
  frontend/src/pages/room/content-share/contentPresentSection.tsx
  frontend/src/pages/room/room.tsx
  frontend/src/styles/animation.ts
  frontend/src/styles/index.ts
  frontend/src/types/index.ts
  frontend/src/types/response.ts
  frontend/src/types/videoPlayer.ts
  frontend/src/utils/index.ts
  frontend/src/utils/youtube.ts
  frontend/vitest.config.ts
Labels: FE

#143 제공되는 랜덤 닉네임을 이쁘게 변경, 질문 추가, 질문 도출 공식 변경
  backend/src/clients/gateway/clients.gateway.ts
  backend/src/clients/service/clients.service.ts
  backend/src/interests/definition/time.unit.ts
  backend/src/rooms/service/rooms.service.ts
Labels: BE

#149 style: 💄 컨텐츠 공유 뷰 스타일 수정
  frontend/src/pages/room/content-share/contentShareView.tsx
  frontend/src/pages/room/content-share/waitingListEmpty.tsx
  frontend/src/pages/room/content-share/waitingListInfo.tsx
  frontend/src/pages/room/room.tsx
Labels: FE

#153 feat: 🎸 시작 이후엔 새로고침 시 알림창 띄우도록
  frontend/src/pages/room/room.tsx
Labels: FE

#158 공유 이미지 레포지토리 분리 및 예외처리 가드생성, 유튜브 링크 유효성 검사 데코레이터, 파이프 구현
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/interests/decorator/is-youtube-link.decorator.ts
  backend/src/interests/dto/interests.youtube.link.dto.ts
  backend/src/interests/gateway/interests.gateway.ts
  backend/src/interests/guard/validate.image.extention.guard.ts
  backend/src/interests/pipe/custom-validation.pipe.ts
  backend/src/interests/repository/interests.image.repository.ts
  backend/src/interests/repository/interests.in-memory.image.repository.ts
  backend/src/interests/repository/interests.in-memory.repository.ts
  backend/src/interests/repository/interests.os.image.repository.ts
  backend/src/interests/repository/interests.repository.provider.ts
  backend/src/interests/repository/interests.repository.ts
  backend/src/interests/service/interests.service.ts
Labels: BE

#164 UI 개선
  frontend/src/components/ParticipantListSidebar.tsx
  frontend/src/components/Player/Player.tsx
  frontend/src/components/ProfileEditButton.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/constants.ts
  frontend/src/constants/radius.ts
  frontend/src/constants/youtube.ts
  frontend/src/pages/room/KeywordsView.tsx
  frontend/src/pages/room/questionsView.tsx
  frontend/src/pages/room/resultInstruction.tsx
  frontend/src/pages/room/resultView.tsx
  frontend/src/pages/room/room.tsx
  frontend/src/stores/radius.ts
Labels: FE
