Repository boostcampwm-2024/web11-road_to_friendly, pull requests merged in 2024-12, with the labels that each got.

#168 docs: ✏️ 주요 기능 이미지 추가
  README.md
Labels: documentation

#167 fix: 🐛 이슈사항들 해결, UI/UX 피드백 반영
  frontend/src/components/Player/ControllerSection.tsx
  frontend/src/components/ProfileEditButton.tsx
  frontend/src/components/ShareButton.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/components/common/Slider.tsx
  frontend/src/pages/room/KeywordsView.tsx
  frontend/src/pages/room/content-share/contentPresentSection.tsx
  frontend/src/pages/room/content-share/contentShareView.tsx
  frontend/src/pages/room/room.tsx
Labels: bug, enhancement, FE

#174 Room에서 발생하는 에러 컴포넌트에 애니메이션 추가
  frontend/src/components/RoomError/RoomAlreadyEnter.tsx
  frontend/src/components/RoomError/RoomDefaultError.tsx
  frontend/src/components/RoomError/RoomError.tsx
  frontend/src/components/RoomError/RoomNotFoundError.tsx
Labels: FE

#175 fix: 🐛 두 번째 영상 공유부터 영상 상태를 조작하면 뜨는 null 관련 에러 해결
  frontend/src/components/Player/Player.tsx
Labels: bug, FE

#176 UI 개선
  frontend/src/components/ParticipantListSidebar.tsx
  frontend/src/components/ProfileEditButton.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/constants/profile.ts
  frontend/src/hooks/useParticipants.ts
  frontend/src/pages/room/questionsView.tsx
  frontend/src/pages/room/room.tsx
  frontend/src/types/ParticipantItem.ts
  frontend/src/types/participant.ts
Labels: FE

#188 resize 이벤트에 따라 뷰포트기준으로 타원반지름 재계산
  frontend/src/components/UserProfile.tsx
  frontend/src/constants/radius.ts
  frontend/src/pages/room/Room.tsx
  frontend/src/stores/radius.ts
  frontend/src/utils/arrangement.ts
  frontend/src/utils/index.ts
Labels: 방 개설 및 참여, FE
